### ISSUE TITLE
Generator gui crashes when fields are empty

### ISSUE THREAD

**Issue by LiBuchauer** [tensionhead/pyBOAT#1]
Hi Gregor,

when using the generator to create synthetic signals, the gui is not very stable to wrong input. E.g., initially understanding that freq1. is the freq at the beginning and freq2 the freq at the end of the signal, I left freq2 empty and the instance crashed. Same happens when you enter 0 into the frequency or amplitude fields. Maybe a warning would be better.

Anyways, it is genuinely nice work.

Lisa

**Comment by tensionhead** [comment]
Hey Lisa,

good catch ;) The SSG was pushed out in one night, so thanks for testing! I put in explicit field validator checks now, version 7.4.4. should fix this. Let me know if it works for you!

**Comment by LiBuchauer** [comment]
Shalom, sorry for the delay, I installed 0.7.5 and it works as expected :-)
