### ISSUE TITLE
Frequent Software Crash on macOS Monterey

### ISSUE THREAD

**Issue by nehabinish** [tensionhead/pyBOAT#12]
Software crash instead of error messages in GUI for several cases such as uploading incompatible dataset, when period is out of bounds or attempting to perform ridge analysis.

**Comment by tensionhead** [comment]
Hey @nehabinish, thx for letting me know! Could you please let me know the pyBOAT version you are using, it's the window title of the start up menu.

**Comment by nehabinish** [comment]
@tensionhead I have not checked out the latest release yet. The crash report is for version 0.9.2

**Comment by tensionhead** [comment]
So I could trace it to an API update of Matplotlib > 3.5.1, thanks again to @nehabinish for reporting! Got fixed with the latest 0.9.6 version.
