### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by orijitghosh** [tensionhead/pyBOAT#2]
Hi,
I'm using Python3.7 and everytime it shows the following error:

_ERROR: Could not find a version that satisfies the requirement pyboat (from versions: none)
ERROR: No matching distribution found for pyboat_

Can you help me through the installation somehow?

Best,
Arijit

**Comment by tensionhead** [comment]
Hi Arjit,

which installation path are you using, Graphical Anaconda or pip? Also,
what's your OS?

**Comment by orijitghosh** [comment]
I'm using pip. Ubuntu 16.04

**Comment by tensionhead** [comment]
Mmh.. a bit of googling seems to indicate that the problem is not the
package (pyboat in this case) but your pip version. Are you using pip3 for
python3?

**Comment by tensionhead** [comment]
Arijit, 
can you install any other package via pip3 onto your system: How does a
``` 
pip3 install wheel
```
go?

**Comment by orijitghosh** [comment]
Hi,
Actually I have spent quite some time on googling and trying to solve the problem. Nothing worked till now. Of course, I am using pip3 and `pip3 install wheel` results in installation of wheel.

**Comment by orijitghosh** [comment]
Okay, after playing around for some more time, I could fix it, but now the problem is somewhere else, though I have PyQt5-5.14 installed, the pyboat distribution is trying to install PyQt5-5.15 and it throws the following error:

`Collecting PyQt5>=5.9.5 (from pyboat)
  Downloading https://files.pythonhosted.org/packages/8c/90/82c62bbbadcca98e8c6fa84f1a638de1ed1c89e85368241e9cc43fcbc320/PyQt5-5.15.0.tar.gz (3.3MB)
    100% |████████████████████████████████| 3.3MB 647kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-pisijvp6/PyQt5/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-pisijvp6/PyQt5/`

How do I circumvent this?
Thank you for your help.

**Comment by tensionhead** [comment]
I am sorry to hear that you continue to have problems with the installation! I am afraid also your latest problem is actually unrelated to pyBOAT, and points towards inconsistencies within the PyQt5 package hosted via pip itself. [Here](https://stackoverflow.com/questions/59711301/install-pyqt5-5-14-1-on-linux) someone describes similar problems with PyQt5 on Ubuntu. Maybe you could try the suggestions from the 1st answer in that SO post? Note that pyboat is happy with any PyQt5 > 5.9.5

I am on Ubuntu 20.04 here, and have no problems with a direct pip installation of pyboat, so I can't reproduce your error. Alternatively you could try to use miniconda: https://docs.conda.io/en/latest/miniconda.html.
It's not as bloated as a full Anaconda install, but gives you the opportunity to install pyboat via
```conda install pyboat``` It will try to fulfill all dependencies, including PyQt5. 

However if your whole Python eco-system runs with pip-installed packages, installing conda on the side might be suboptimal for you. So as a last alternative you could use the ```flit``` build system that I used to make the Python package for pyboat, and try to install from source:
```pip3 install flit```
Then download the pyboat github repo here, cd into it and run:
```flit build && flit install```
That should also install pyboat for you. However you will still need a successful PyQt5 installation.

Hope that helps!

**Comment by orijitghosh** [comment]
Thanks, I was finally able to install it with Miniconda. But now when I am going to start pyBOAT, it shows me the following error, I understand it has something to do with the display, but don't know exactly what. Sorry for disturbing you again and again!
This particular installment issue has been solved though.

**Comment by tensionhead** [comment]
yeah, I am also a bit surprised, the whole point of packaging/distribution systems like pip and conda is to avoid exactly those kind of problems, glad you managed after all ;)

So the ```XDG_RUNTIME_DIR``` should be there by default on any debian like system, are you sitting in front of the machine+monitor you are trying to run pyboat on (so it's not a remote session)? Could you maybe paste the output of:

```ls -ltr $XDG_RUNTIME_DIR```

here?

**Comment by orijitghosh** [comment]
Yes, it's weird why pip is throwing so many problems. I am using a machine+monitor setup, not a remote session.

This is the output of `ls -ltr $XDG_RUNTIME_DIR`:
```
total 52
drwxrwxrwx 1 cryptodice cryptodice  4096 May 27 14:31 scripts
-rwxrwxrwx 1 cryptodice cryptodice  1813 May 27 14:31 scripting_template.py
-rwxrwxrwx 1 cryptodice cryptodice  1163 May 27 14:31 scripting_templateOOP.py
-rwxrwxrwx 1 cryptodice cryptodice  7583 May 27 14:31 README.md
-rwxrwxrwx 1 cryptodice cryptodice   602 May 27 14:31 pyproject.toml
-rwxrwxrwx 1 cryptodice cryptodice   257 May 27 14:31 MANIFEST.in
-rwxrwxrwx 1 cryptodice cryptodice 35067 May 27 14:31 LICENSE
drwxrwxrwx 1 cryptodice cryptodice  4096 May 27 14:31 example_data
drwxrwxrwx 1 cryptodice cryptodice  4096 May 27 14:31 doc
-rwxrwxrwx 1 cryptodice cryptodice   454 May 27 14:31 CHANGELOG.md
drwxrwxrwx 1 cryptodice cryptodice  4096 Jun  7 18:48 pyboat
drwxrwxrwx 1 cryptodice cryptodice  4096 Jun  8 21:19 env
drwxrwxrwx 1 cryptodice cryptodice  4096 Jun  8 21:23 dist
```
Also, I can successfully run the `scripting_templateOOP.py`, but it does not show any output. Is that supposed to happen?

**Comment by tensionhead** [comment]
Yep, the scripting template is supposed to run in an interactive (ipython-)session, then you can see the output figures. But good point, maybe I should also save the figures out for non-interactive demonstration. Try running the template in an ipython (highly recommended python interpreter) console for now ;)

The problem with your ```XDG_RUNTIME_DIR``` is very odd, usually that only happens if you are not the user who started the Xserver session, or as I mentioned above during a remote session.
What strike me was that path from your post above:
```cryptodice@NirakarNeo:/mnt/c/Users/ariji$``` this points to exactly such a problem, the user is called ```cryptodice``` but you are in the (```/mnt/c/...```?) home directory of ```arijit```? Also the directory itself contains nothing but the pyboat repo? What is the runtime directory itself, on my system

```echo $XDG_RUNTIME_DIR```

outputs ```/run/user/1000```, what is it in your case?
Anyways, I am afraid that again has nothing to do with pyboat itself, but here with the way your system is set up. Also Ubuntu 16.X is slightly outdated by now (although still supported for 1 more year), my suggestion: put a modern Ubuntu on a USB (at least 2Gb) stick, boot the live system and do a fresh (non-persistent) installation: 

```sudo apt install pip3``` 
```pip3 install pyboat```
```pyboat```

**Comment by orijitghosh** [comment]
I am actually using linux susbsyetm under win10. So far I have not faced any problems like this.
But as you suggested I sideloaded Ubuntu-20.04, and did a clean installation of pip and voila, pyboat got installed. When I try to run it, I see this error now:

```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
```
I know, this is not a pyboat problem, so I am closing this issue, thank you so much, Any further help will be very much appreciated.

**Comment by tensionhead** [comment]
Ah, you are on a linux subsystem.. Ok, here I really have to pass, as I have zero experiences with such a setup. I guess googling for Qt running problems on such subsystems under win10 should help.

Btw, you can also install pyboat directly onto windows, preferably via the graphical installation route ;)
